name: home_presentation
description: "A Flutter package for the presentation layer of the home feature."
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  tt_i18n:

  hooks_riverpod:
  flutter_hooks:
  riverpod_annotation:

  go_router:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Local packages
  tt_linter:

  build_runner:
  riverpod_generator:

  mockito:

flutter:
  generate: true
