// Mocks generated by Mockito 5.4.6 from annotations
// in game_domain/test/ut/repository/mock_current_game_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:game_domain/src/entity/current_game_entity.dart' as _i2;
import 'package:game_domain/src/repository/current_game_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCurrentGameEntity_0 extends _i1.SmartFake
    implements _i2.CurrentGameEntity {
  _FakeCurrentGameEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CurrentGameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrentGameRepository extends _i1.Mock
    implements _i3.CurrentGameRepository {
  MockCurrentGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CurrentGameEntity get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _FakeCurrentGameEntity_0(
              this,
              Invocation.method(#get, []),
            ),
          )
          as _i2.CurrentGameEntity);

  @override
  _i4.Future<_i2.CurrentGameEntity> save(_i2.CurrentGameEntity? settings) =>
      (super.noSuchMethod(
            Invocation.method(#save, [settings]),
            returnValue: _i4.Future<_i2.CurrentGameEntity>.value(
              _FakeCurrentGameEntity_0(
                this,
                Invocation.method(#save, [settings]),
              ),
            ),
          )
          as _i4.Future<_i2.CurrentGameEntity>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
