name: user_domain
description: "A Flutter package for the domain layer of the user feature."
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod:
  riverpod_annotation:

  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Local packages
  tt_linter:

  build_runner:
  riverpod_generator:
  freezed:

  mockito:

flutter:
  generate: true
