name: triple_t_workspace
environment:
  sdk: 3.10.8

dependencies:
  flutter:
    sdk: flutter

  go_router: ^17.1.0
  hooks_riverpod: ^3.0.0
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^4.0.0

dev_dependencies:
  riverpod_generator: ^4.0.0
  build_runner: ^2.11.0
  melos: ^7.4.0

flutter:
  generate: true

workspace:
  - apps/triple_t
  - packages/triple_t_i18n

melos:
  runPubGetInParallel: false
  useRootAsPackage: false

  command:
    bootstrap:
      hooks:
        post: |
          flutter pub get
          melos list --cycles

  scripts:
    ############################################################################
    # Installation
    ############################################################################
    generate:
      description: Generate model for specific package
      run: melos exec --order-dependents -- "dart run build_runner build --delete-conflicting-outputs"
      concurrency: 3
      packageFilters:
        dependsOn:
          - build_runner

    generate:all:
      description: Generate model for all packages
      run: |
        melos run generate && melos run generate:l10n

    generate:l10n:
      description: Generate localization files
      run: melos exec --scope="triple_t_i18n" -- "flutter gen-l10n"

    clean:deep:
      description: Clean all project
      run: |
        melos exec --fail-fast -- "flutter clean" && find . -type f -name "*.lock" -delete && find . -type f -name "*.freezed.dart" -delete && find . -type f -name "*.g.dart" -delete && find . -type f -name "*.mocks.dart" -delete
      concurrency: 1

    ############################################################################
    # Tests
    ############################################################################
