name: game_data
description: "A Flutter package for the data layer of the game feature."
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  # Local packages
  tt_database:
  game_domain:

  hooks_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

  # Local packages
  tt_linter:
