name: triple_t
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Local packages
  tt_i18n:
  tt_database:

  error_presentation:
  game_presentation:
  home_presentation:
  settings_domain:
  settings_presentation:
  statistics_presentation:
  user_data:
  user_presentation:

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

  hooks_riverpod:
  flutter_hooks:
  riverpod_annotation:

  freezed_annotation:
  json_annotation:

  go_router:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Local packages
  tt_linter:

  build_runner:
  riverpod_generator:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
