name: tt_linter
description: "A Flutter package for linting and code analysis in the TT project."
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.0

  flutter_lints: ^6.0.0

dev_dependencies:
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.0
