name: user_data
description: "A Flutter package for the data layer of the user feature."
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  tt_database:

  hooks_riverpod:

  freezed_annotation:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Local packages
  tt_linter:

  build_runner:
  freezed:
  json_serializable:

  mockito:

flutter:
  generate: true
