name: settings_domain
description: "A Flutter package for the domain layer of the settings feature."
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod:
  riverpod_annotation:

  freezed_annotation:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

  # Local packages
  tt_linter:

  build_runner:
  riverpod_generator:
  freezed:
  json_serializable:

flutter:
  generate: true
